name: An Introduction to Clustering
category: analysis
authors: ""
shortdesc: This course illustrates the application of a variety of clustering methods to an MD trajectory, comparing their performance.
longdesc: ""
